// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1KrtrT1LWPUO26_yv65W9wkTIG_O8E-U',
    appId: '1:916224715832:web:3615cfa60c5d5cfad30acd',
    messagingSenderId: '916224715832',
    projectId: 'football-club-app-5ee42',
    authDomain: 'football-club-app-5ee42.firebaseapp.com',
    storageBucket: 'football-club-app-5ee42.firebasestorage.app',
    measurementId: 'G-1V0YSG8DXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfDoWfBQtJp1eF-kbZVYNNcqBP7-2vdeo',
    appId: '1:916224715832:android:da8c684884b31c6cd30acd',
    messagingSenderId: '916224715832',
    projectId: 'football-club-app-5ee42',
    storageBucket: 'football-club-app-5ee42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVFiB3nPcVfLZDiL4mA6tcfK0PrDG240A',
    appId: '1:916224715832:ios:efc6ba7e82c15d5ad30acd',
    messagingSenderId: '916224715832',
    projectId: 'football-club-app-5ee42',
    storageBucket: 'football-club-app-5ee42.firebasestorage.app',
    iosBundleId: 'com.example.basedProjectListClubSepakBola',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVFiB3nPcVfLZDiL4mA6tcfK0PrDG240A',
    appId: '1:916224715832:ios:efc6ba7e82c15d5ad30acd',
    messagingSenderId: '916224715832',
    projectId: 'football-club-app-5ee42',
    storageBucket: 'football-club-app-5ee42.firebasestorage.app',
    iosBundleId: 'com.example.basedProjectListClubSepakBola',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1KrtrT1LWPUO26_yv65W9wkTIG_O8E-U',
    appId: '1:916224715832:web:4a838d73aa3cd3c1d30acd',
    messagingSenderId: '916224715832',
    projectId: 'football-club-app-5ee42',
    authDomain: 'football-club-app-5ee42.firebaseapp.com',
    storageBucket: 'football-club-app-5ee42.firebasestorage.app',
    measurementId: 'G-9WJFLVLCK3',
  );
}
